project:
  type: website

website:
  site-url: https://norhendra-isss608.netlify.app/
  title: "ISSS608"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3A"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
        - text: "Hands-on Exercise 3B"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
        - text: "Hands-on Exercise 4A"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
        - text: "Hands-on Exercise 4B"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
        - text: "Hands-on Exercise 4C"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
        - text: "Hands-on Exercise 4D"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex4d.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 8A"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08a.html"
        - text: "Hands-on Exercise 8B"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08b.html"
        - text: "Hands-on Exercise 8C"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08c.html"
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1: Phase 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 1: Phase 2"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01p2.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex03.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 5"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
            
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

