project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3A"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
        - text: "Hands-on Exercise 3B"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"

    - text: "Take-home Exercise"  
      menu:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
            
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

