project:
  type: website

website:
  title: "Hendra's VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise"
          href: "In-class_Ex"
      menu:
        - text: "Take-home Exercise"
          href: "Take-home_Ex"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
            
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

